on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: deploy to prod
    runs-on: windows-2022
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
      - name: Install Dependencies & Build
        run: |
          npm install
          npx nx run wladcy-kostek-app:build --configuration=production
      - name: FTP Interactions
        uses: priradev/ftp-interactions@v0.2.9-beta
        with:
          host: 20.82.145.167
          # Port for the FTP host.
          port: 21
          # Username for the FTP host.
          username: wkenv
          # Password for the FTP host.
          password: u0RZ16EFAnAx
          # Local directory from which to upload.
          localDir: dist/apps/wladcy-kostek-app
          # FTP Action: None | Copy | DeleteAppOfflineHtm.
          ftpAction: Copy
          # Ignore certificate errors.
          ignoreCertificateErrors: true
          
