on:
  push:
    branches:
    - master
jobs:
  my_job:
    name: deploy to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - run: npm ci
      - run: npx nx run wladcy-kostek-app:build --configuration=production
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.82.145.167
          port: 21
          username: wkenv-ftp
          password: u0RZ16EFAnAx
          local-dir: dist/apps/
          
