on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - run: npm ci
      - run: npx nx run wladcy-kostek-app:build --configuration=production
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: dist
          path: dist/apps
  deploy:
    name: Deploy Web App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.7
        with:
          name: dist
          path: .
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.82.145.167
          port: 21
          username: ${{ secrets.ftp_acc }}
          password: ${{ secrets.ftp_password }}
  build_android:
    name: Build Android App
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - run: npm i -g @bubblewrap/cli
      - run: cd ./android
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - run: no | bubblewrap build --signingKeyPath="${{ secrets.android_key }}" --signingKeyAlias="${{ secrets.android_key }}" 
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: android
          path: android
  deploy_android:
    name: Deploy Android App
    needs: build_android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: android
          path: .
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 20.82.145.167
          port: 21
          username: ${{ secrets.ftp_acc }}
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/gradle/**
            **/app/**
            **/gradle/**
            build.gradle
            gradle.properties
            gradlew
            gradlew.bat
            manifest-checksum.txt
            settings.gradle
            store_icon.png
            twa-manifest.json
            android.keystore
